### ISSUE TITLE
vite5? An error occurs in babel-plugin-twin after vite update.

### ISSUE THREAD

**Issue by Hansanghyeon** [ben-rogerson/babel-plugin-twin#13]
It seems like you're encountering an issue with Storybook's Vite builder. The problem appears to be related to using a virtual package with a name that includes a . (dot), and it seems that the package cannot be found when cloned.

```
[vite:react-babel] /virtual:/@storybook/builder-vite/vite-app.js: Cannot find module 'twin.macro' from '/virtual:/@storybook/builder-vite'
file: /virtual:/@storybook/builder-vite/vite-app.js
=> Failed to build the preview
Error: /virtual:/@storybook/builder-vite/vite-app.js: Cannot find module 'twin.macro' from '/virtual:/@storybook/builder-vite'
    at Function.resolveSync [as sync] (./node_modules/resolve/lib/sync.js:111:15)
    at nodeResolvePath (./node_modules/babel-plugin-macros/dist/index.js:62:18)
    at applyMacros (./node_modules/babel-plugin-macros/dist/index.js:203:23)
    at ImportDeclaration (./node_modules/babel-plugin-macros/dist/index.js:110:28)
    at NodePath._call (./node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (./node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (./node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (./node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (./node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (./node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (./node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (./node_modules/@babel/traverse/lib/index.js:52:34)
    at NodePath.traverse (./node_modules/@babel/traverse/lib/path/index.js:101:24)
    at PluginPass.Program (./node_modules/babel-plugin-macros/dist/index.js:91:18)
    at newFn (./node_modules/@babel/traverse/lib/visitors.js:160:14)
    at NodePath._call (./node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (./node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (./node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (./node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (./node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (./node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (./node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (./node_modules/@babel/traverse/lib/index.js:52:34)
    at transformFile (./node_modules/@babel/core/lib/transformation/index.js:82:31)
    at transformFile.next (<anonymous>)
    at run (./node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at transform (./node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (./node_modules/gensync/index.js:261:32)
    at ./node_modules/gensync/index.js:273:13
    at async.call.result.err.err (./node_modules/gensync/index.js:223:11)
    at ./node_modules/gensync/index.js:189:28
    at ./node_modules/@babel/core/lib/gensync-utils/async.js:67:7
    at ./node_modules/gensync/index.js:113:33
    at step (./node_modules/gensync/index.js:287:14)
    at ./node_modules/gensync/index.js:273:13
    at async.call.result.err.err (./node_modules/gensync/index.js:223:11)
```

- `storybook@7.5.1`
- `vite@5.0.0`
- `babel-plugin-twin@1.1.0`
- `twin.macro@3.4.0`

https://github.com/storybookjs/builder-vite/issues/535
https://github.com/storybookjs/builder-vite/issues/367

I looked into these issues.

**Comment by ben-rogerson** [comment]
Hey there, could you provide a minimal reproduction of the bug? Would really help diagnose the issue.

**Comment by socker210** [comment]
Same here.

```javasscript
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [
    react({
      jsxRuntime: 'automatic',
      jsxImportSource: '@emotion/react',
      babel: {
        plugins: ['babel-plugin-twin', 'babel-plugin-macros', '@emotion'],
      },
    }),
  ],
})
```

@ben-rogerson here is the vite config for storybook.
